### ISSUE TITLE
better scheduling in froglock

### ISSUE THREAD

**Issue by c-cube** [c-cube/frog-utils#13]
- use a priority queue (to have different priorities)
- be fair w.r.t users?
- add a `-j <num cores>` option and run several jobs at once if they won't overlap (advanced)

**Comment by Gbury** [comment]
I think that using a priority queue for jobs in froglock, and adding an argument to specify the priority when using the command line tool could be useful, I'll probably do it soon.
Additionally, it coud be nice if there was a way for froglock to pause and resume jobs properly (using, for instance signals like sigstp and sigcont), so that a large job can be temporarily interrupted while a job with higher priority is run.

**Comment by Gbury** [comment]
So can we close this one, or do we want more options for scheduling (such as user fairness, ....) ?
